version: '3'
services:
  apicallapp:
    build:
      context: ./apicallapp
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    environment:
      - CALL_ME_HOST=http://callme:8001/callme
      - HOST_IP=apicallapp
    restart: unless-stopped

  callme:
    build:
      context: ./callme
    networks:
      - mynetwork
    ports:
      - "8001:8000"
    restart: unless-stopped

networks:
  mynetwork:
    name: mynetwork
