---
- name: Install Docker and Docker Swarm
  become: true

  tasks:
    - name: Install Docker dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        state: present
      become: true

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      become: true

    - name: Install Docker engine
      apt:
        name: docker-ce
        state: present
      become: true

    - name: Install Docker Swarm
      command: docker swarm init --advertise-addr <your_host_ip>
      become: true
      args:
        creates: /root/.docker/swarm

    - name: Retrieve Docker Swarm join token
      shell: docker swarm join-token -q worker
      become: true
      register: join_token

    - name: Show Docker Swarm join token
      debug:
        var: join_token.stdout_lines


