---
    # - name: Set AWS CLI credentials
    #   aws_configure:
    #     aws_access_key_id: "{{ aws_access_key_id }}"
    #     aws_secret_access_key: "{{ aws_secret_access_key }}"
    #     region: "{{ aws_region }}"
  
    - name: Get ECR Login Password
      command: aws ecr get-login-password --region us-east-1
      register: ecr_login_password

    - name: Docker Login to ECR
      command: docker login --username AWS --password-stdin "{{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com"
      args:
        stdin: "{{ ecr_login_password.stdout }}"
